#!/usr/bin/env bash
# This script changes the home IP address by restarting the network interface.
[ "$EUID" -ne 0 ] && echo "Please run as root" && exit 1

echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
